### PR TITLE
fix(core): check chunk size

### PR DESCRIPTION
**Pull request by kukhariev**

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Thanks, but the `content-length` header can be invalid so I think we should also limit the amount of data piped into the file: https://github.com/kukhariev/node-uploadx/blob/master/packages/core/src/storages/disk-storage.ts#L103

**Comment by rigelk** [comment]
I would suggest using https://github.com/Sumolari/stream-size with the validated `content-length` header.

**Comment by kukhariev** [comment]
Probably this will work:
```ts
protected _write(part: FilePart & File): Promise<number> {
    return new Promise((resolve, reject) => {
      const path = this._getPath(part.name);
      if (hasContent(part)) {
        const file = getWriteStream(path, part.start);
        const content = part.body.pipe(getSizeTransform(part.size - part.start));
        content.on('error', () => resolve(INVALID_RANGE));
        content.pipe(file).on('finish', () => resolve(part.start + file.bytesWritten));
....
```

**Comment by Chocobozzz** [comment]
Seems to work on my side, thanks

**Pull request merged**
